name: nya_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  intl: ^0.17.0
  provider: ^6.0.1
  json_annotation: ^4.4.0
  flutter:
    sdk: flutter

  http: 0.13.4

  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git

  shared_preferences: ^2.0.13

  cupertino_icons: ^1.0.2

  flutter_svg: ^1.0.3

dev_dependencies:
  json_serializable: ^6.1.5
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: ElectroHarmonix
      fonts:
        - asset: assets/fonts/electroharmonix.ttf

